### ISSUE TITLE
"Daily activity metrics.csv" doesn't exist

### ISSUE THREAD

**Issue by CharlesButcher** [DavidMetcalfe/Google-Fit-consolidate-data-export#1]
Thanks for this really useful script! As a highly inexperienced Python user I was puzzled by an error that turned out to result from the fact that my Google Fit export did not contain the file "Daily activity metrics.csv". I commented out line 44 and all was fine. A refinement would be to check for the presence of this file before trying to delete it.

**Comment by DavidMetcalfe** [comment]
Thanks for catching that! Not sure why the Google Fit data export didn't include that file in your case, but I've wrapped that bit of code in a try/except. Let me know if you have any issues with the updated script.
